name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:

  check-gentxs:
    name: Check gentxs validity
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Setup Python 🐍
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.5'

      - name: Check gentxs validity ✅
        run: |
          pip3 install -r scripts/requirements.txt
          python scripts/check-gentx.py "$GITHUB_WORKSPACE/gentxs"
      - uses: actions/upload-artifact@v3
        with:
          name: genesis.json
          path: genesis/genesis.json

        

  collect-genesis:
    name: Collect genesis test
    runs-on: ubuntu-latest
    needs:
      - check-gentxs
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Download Canine 💿
        run: |
          sudo wget -O /usr/local/bin/canined https://github.com/JackalLabs/canine-chain/releases/download/v1.0.0/canined-Linux
          sudo chmod +x /usr/local/bin/canined
          sudo wget -O /lib/libwasmvm.x86_64.so https://github.com/CosmWasm/wasmvm/raw/v1.1.1/internal/api/libwasmvm.x86_64.so
      - name: Collect genesis transactions 📮
        run: |
          canined init node
          cp genesis/genesis.json ~/.canine/config/genesis.json
          cp -a gentx/. ~/.canine/config/gentx/
          canined collect-gentxs

      - name: Validate genesis ✅
        run: |
          canined validate-genesis ~/.canine/config/genesis.json

      - name: Start chain ⛓
        run: |
          canined start > output.txt 2>&1 &

      - name: Test liveness ✅
        run: |
          sleep 30
          cat output.txt
          if [[ $(cat output.txt | grep "Genesis time is in the future") ]]; then
            echo "Chain starting"
            exit 0
          else
            echo "Chain not started"
            exit 1
          fi
